import {
  Code2,
  FunctionSquare,
  Monitor,
  Globe,
  Server,
  Cloud,
  Container,
  Brain,
  Network,
  Cpu,
  Bot,
  Workflow,
  Shield,
  Building2,
  type LucideIcon,
} from "lucide-react";

export interface CurriculumTopic {
  id: string;
  name: string;
  icon: LucideIcon;
  color: string;
  progress: number;
  modules: number;
  completed: number;
  description: string;
  topics: string[];
}

export const curriculum: CurriculumTopic[] = [
  {
    id: "programming",
    name: "Programming",
    icon: Code2,
    color: "text-accent-blue",
    progress: 72,
    modules: 24,
    completed: 17,
    description: "Core programming languages and paradigms",
    topics: ["TypeScript", "Python", "Rust", "Go", "Functional Programming"],
  },
  {
    id: "mathematics",
    name: "Mathematics",
    icon: FunctionSquare,
    color: "text-accent-purple",
    progress: 45,
    modules: 20,
    completed: 9,
    description: "Discrete math, linear algebra, calculus",
    topics: ["Linear Algebra", "Calculus", "Discrete Math", "Statistics", "Probability"],
  },
  {
    id: "computer-science",
    name: "Computer Science",
    icon: Monitor,
    color: "text-accent-cyan",
    progress: 58,
    modules: 18,
    completed: 10,
    description: "Algorithms, data structures, theory",
    topics: ["Data Structures", "Algorithms", "Complexity Theory", "Compiler Design", "OS"],
  },
  {
    id: "web-development",
    name: "Web Development",
    icon: Globe,
    color: "text-accent-green",
    progress: 81,
    modules: 16,
    completed: 13,
    description: "Frontend, backend, full-stack engineering",
    topics: ["React", "Next.js", "CSS/Animation", "Web APIs", "Performance"],
  },
  {
    id: "backend",
    name: "Backend Engineering",
    icon: Server,
    color: "text-accent-blue",
    progress: 65,
    modules: 22,
    completed: 14,
    description: "APIs, databases, microservices",
    topics: ["REST/GraphQL", "gRPC", "PostgreSQL", "Redis", "Message Queues"],
  },
  {
    id: "cloud",
    name: "Cloud Infrastructure",
    icon: Cloud,
    color: "text-accent-cyan",
    progress: 38,
    modules: 20,
    completed: 7,
    description: "AWS, GCP, Azure, serverless",
    topics: ["AWS Core", "Kubernetes", "Terraform", "Serverless", "Cloud Design"],
  },
  {
    id: "devops",
    name: "DevOps & SRE",
    icon: Container,
    color: "text-accent-amber",
    progress: 42,
    modules: 18,
    completed: 7,
    description: "CI/CD, monitoring, reliability",
    topics: ["Docker", "CI/CD Pipelines", "Observability", "Incident Response", "SLOs"],
  },
  {
    id: "machine-learning",
    name: "Machine Learning",
    icon: Brain,
    color: "text-accent-purple",
    progress: 31,
    modules: 24,
    completed: 7,
    description: "ML fundamentals, models, pipelines",
    topics: [
      "Supervised Learning",
      "Unsupervised Learning",
      "Feature Engineering",
      "Model Evaluation",
      "ML Pipelines",
    ],
  },
  {
    id: "deep-learning",
    name: "Deep Learning",
    icon: Network,
    color: "text-accent-purple",
    progress: 22,
    modules: 20,
    completed: 4,
    description: "Neural networks, architectures, training",
    topics: ["CNNs", "RNNs/LSTMs", "Transformers", "GANs", "Diffusion Models"],
  },
  {
    id: "transformers",
    name: "Transformers & Attention",
    icon: Cpu,
    color: "text-accent-green",
    progress: 18,
    modules: 16,
    completed: 3,
    description: "Attention is all you need",
    topics: [
      "Attention Mechanism",
      "BERT",
      "GPT Architectures",
      "Fine-tuning",
      "Inference Optimization",
    ],
  },
  {
    id: "llms",
    name: "Large Language Models",
    icon: Bot,
    color: "text-accent-purple",
    progress: 15,
    modules: 20,
    completed: 3,
    description: "LLM engineering and prompting",
    topics: ["Prompt Engineering", "RAG Systems", "Agent Frameworks", "Safety", "Evaluation"],
  },
  {
    id: "ai-agents",
    name: "AI Agents",
    icon: Workflow,
    color: "text-accent-cyan",
    progress: 10,
    modules: 14,
    completed: 1,
    description: "Autonomous AI agent systems",
    topics: ["Agent Architecture", "Tool Use", "Memory Systems", "Multi-agent", "Planning"],
  },
  {
    id: "mlops",
    name: "MLOps",
    icon: Container,
    color: "text-accent-blue",
    progress: 12,
    modules: 16,
    completed: 2,
    description: "ML lifecycle management",
    topics: [
      "Experiment Tracking",
      "Model Registry",
      "Feature Stores",
      "Model Serving",
      "Monitoring",
    ],
  },
  {
    id: "security",
    name: "Security Engineering",
    icon: Shield,
    color: "text-accent-red",
    progress: 25,
    modules: 18,
    completed: 4,
    description: "Application and infrastructure security",
    topics: ["Web Security", "Auth/AuthZ", "Cryptography", "Network Security", "Supply Chain"],
  },
  {
    id: "system-design",
    name: "System Design",
    icon: Building2,
    color: "text-accent-green",
    progress: 55,
    modules: 20,
    completed: 11,
    description: "Distributed systems architecture",
    topics: ["Consensus", "Consistency Models", "Partitioning", "Caching", "Observability"],
  },
];
