export interface LearningResource {
  id: string;
  title: string;
  author: string;
  type: "book" | "course" | "article" | "video" | "paper" | "tool" | "documentation";
  url?: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  topics: string[];
  duration: string;
  completed?: boolean;
}

export const resources: LearningResource[] = [
  {
    id: "ddia",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    type: "book",
    difficulty: "intermediate",
    topics: ["distributed-systems", "architecture"],
    duration: "30h",
  },
  {
    id: "hands-on-ml",
    title: "Hands-On Machine Learning",
    author: "Aurélien Géron",
    type: "book",
    difficulty: "intermediate",
    topics: ["ml", "scikit-learn"],
    duration: "40h",
  },
  {
    id: "deep-learning-book",
    title: "Deep Learning",
    author: "Goodfellow, Bengio, Courville",
    type: "book",
    difficulty: "advanced",
    topics: ["deep-learning", "neural-networks"],
    duration: "50h",
  },
  {
    id: "rust-book",
    title: "The Rust Programming Language",
    author: "Mozilla",
    type: "book",
    difficulty: "beginner",
    topics: ["rust"],
    duration: "20h",
  },
  {
    id: "ts-handbook",
    title: "TypeScript Handbook",
    author: "Microsoft",
    type: "documentation",
    difficulty: "beginner",
    topics: ["typescript"],
    duration: "10h",
  },
  {
    id: "mit-6824",
    title: "MIT 6.824: Distributed Systems",
    author: "MIT",
    type: "course",
    difficulty: "advanced",
    topics: ["distributed-systems"],
    duration: "60h",
  },
  {
    id: "fast-ai",
    title: "Fast.ai Practical Deep Learning",
    author: "Jeremy Howard",
    type: "course",
    difficulty: "beginner",
    topics: ["deep-learning"],
    duration: "40h",
  },
  {
    id: "huggingface-nlp",
    title: "Hugging Face NLP Course",
    author: "Hugging Face",
    type: "course",
    difficulty: "intermediate",
    topics: ["nlp", "transformers"],
    duration: "20h",
  },
  {
    id: "langchain-docs",
    title: "LangChain Documentation",
    author: "LangChain",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["llm", "agents"],
    duration: "15h",
  },
  {
    id: "langgraph-docs",
    title: "LangGraph Documentation",
    author: "LangChain",
    type: "documentation",
    difficulty: "advanced",
    topics: ["agents", "workflows"],
    duration: "10h",
  },
  {
    id: "attention-paper",
    title: "Attention Is All You Need",
    author: "Vaswani et al.",
    type: "paper",
    difficulty: "advanced",
    topics: ["transformers", "attention"],
    duration: "3h",
  },
  {
    id: "kafka-docs",
    title: "Apache Kafka Documentation",
    author: "Apache",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["kafka", "streaming"],
    duration: "15h",
  },
  {
    id: "pg-docs",
    title: "PostgreSQL Documentation",
    author: "PostgreSQL Global Development Group",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["postgresql", "databases"],
    duration: "20h",
  },
  {
    id: "aws-saa",
    title: "AWS Solutions Architect Associate",
    author: "Amazon",
    type: "course",
    difficulty: "intermediate",
    topics: ["aws", "cloud"],
    duration: "40h",
  },
  {
    id: "terraform-up",
    title: "Terraform: Up & Running",
    author: "Yevgeniy Brikman",
    type: "book",
    difficulty: "intermediate",
    topics: ["terraform", "iac"],
    duration: "15h",
  },
  {
    id: "sre-book",
    title: "Site Reliability Engineering",
    author: "Google",
    type: "book",
    difficulty: "intermediate",
    topics: ["sre", "reliability"],
    duration: "25h",
  },
  {
    id: "o11y-book",
    title: "Observability Engineering",
    author: "Charity Majors et al.",
    type: "book",
    difficulty: "intermediate",
    topics: ["observability", "monitoring"],
    duration: "20h",
  },
  {
    id: "platform-eng-book",
    title: "Platform Engineering",
    author: "Camberley et al.",
    type: "book",
    difficulty: "intermediate",
    topics: ["platform-engineering"],
    duration: "15h",
  },
  {
    id: "microservices-patterns",
    title: "Microservices Patterns",
    author: "Chris Richardson",
    type: "book",
    difficulty: "intermediate",
    topics: ["microservices", "architecture"],
    duration: "25h",
  },
  {
    id: "api-design-book",
    title: "API Design Patterns",
    author: "JJ Geewax",
    type: "book",
    difficulty: "intermediate",
    topics: ["api", "design"],
    duration: "20h",
  },
  {
    id: "docker-deep",
    title: "Docker Deep Dive",
    author: "Nigel Poulton",
    type: "book",
    difficulty: "intermediate",
    topics: ["docker", "containers"],
    duration: "12h",
  },
  {
    id: "ckad-guide",
    title: "CKAD Exam Guide",
    author: "Benjamin Muschko",
    type: "book",
    difficulty: "intermediate",
    topics: ["kubernetes"],
    duration: "25h",
  },
  {
    id: "mlops-book",
    title: "MLOps: Machine Learning Operations",
    author: "Noor et al.",
    type: "book",
    difficulty: "intermediate",
    topics: ["mlops"],
    duration: "20h",
  },
  {
    id: "ml-engineering",
    title: "Machine Learning Engineering",
    author: "Andriy Burkov",
    type: "book",
    difficulty: "intermediate",
    topics: ["ml", "engineering"],
    duration: "20h",
  },
  {
    id: "statistical-learning",
    title: "An Introduction to Statistical Learning",
    author: "James, Witten, Hastie, Tibshirani",
    type: "book",
    difficulty: "intermediate",
    topics: ["statistics", "ml"],
    duration: "30h",
  },
  {
    id: "essence-linalg",
    title: "Essence of Linear Algebra",
    author: "3Blue1Brown",
    type: "video",
    difficulty: "beginner",
    topics: ["mathematics", "linear-algebra"],
    duration: "4h",
  },
  {
    id: "statistical-thinking",
    title: "Statistical Thinking for Data Science",
    author: "Stanford",
    type: "course",
    difficulty: "intermediate",
    topics: ["statistics"],
    duration: "30h",
  },
  {
    id: "d2l",
    title: "Dive into Deep Learning",
    author: "Zhang, Lipton, Li, Smola",
    type: "book",
    difficulty: "intermediate",
    topics: ["deep-learning"],
    duration: "40h",
  },
  {
    id: "pytorch-docs",
    title: "PyTorch Documentation",
    author: "Meta",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["pytorch", "deep-learning"],
    duration: "15h",
  },
  {
    id: "kubeflow-docs",
    title: "Kubeflow Documentation",
    author: "Kubeflow",
    type: "documentation",
    difficulty: "advanced",
    topics: ["mlops", "kubernetes"],
    duration: "10h",
  },
  {
    id: "mlflow-docs",
    title: "MLflow Documentation",
    author: "Databricks",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["mlops", "experiment-tracking"],
    duration: "8h",
  },
  {
    id: "ai-safety-papers",
    title: "AI Safety: A Reading List",
    author: "Various",
    type: "paper",
    difficulty: "advanced",
    topics: ["ai-safety", "alignment"],
    duration: "15h",
  },
  {
    id: "evals-framework",
    title: "OpenAI Evals Framework",
    author: "OpenAI",
    type: "tool",
    difficulty: "intermediate",
    topics: ["evaluation", "llm"],
    duration: "5h",
  },
  {
    id: "agent-patterns",
    title: "AI Agent Patterns",
    author: "Anthropic",
    type: "article",
    difficulty: "intermediate",
    topics: ["agents", "patterns"],
    duration: "2h",
  },
  {
    id: "llm-apps",
    title: "Building LLM Apps",
    author: "Valentina Alto",
    type: "book",
    difficulty: "intermediate",
    topics: ["llm", "applications"],
    duration: "15h",
  },
  {
    id: "rust-by-example",
    title: "Rust by Example",
    author: "Mozilla",
    type: "documentation",
    difficulty: "beginner",
    topics: ["rust"],
    duration: "10h",
  },
  {
    id: "rustlings",
    title: "Rustlings",
    author: "Rust Community",
    type: "tool",
    difficulty: "beginner",
    topics: ["rust"],
    duration: "5h",
  },
  {
    id: "rust-nomicon",
    title: "The Rustonomicon",
    author: "Mozilla",
    type: "book",
    difficulty: "advanced",
    topics: ["rust", "unsafe"],
    duration: "10h",
  },
  {
    id: "rust-atomics",
    title: "Rust Atomics and Locks",
    author: "Mara Bos",
    type: "book",
    difficulty: "advanced",
    topics: ["rust", "concurrency"],
    duration: "15h",
  },
  {
    id: "async-rust-book",
    title: "Asynchronous Programming in Rust",
    author: "Various",
    type: "book",
    difficulty: "intermediate",
    topics: ["rust", "async"],
    duration: "12h",
  },
  {
    id: "tokio-docs",
    title: "Tokio Documentation",
    author: "Tokio Contributors",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["rust", "async"],
    duration: "10h",
  },
  {
    id: "go-book",
    title: "The Go Programming Language",
    author: "Donovan & Kernighan",
    type: "book",
    difficulty: "beginner",
    topics: ["go"],
    duration: "20h",
  },
  {
    id: "grpc-docs",
    title: "gRPC Documentation",
    author: "Google",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["grpc", "api"],
    duration: "8h",
  },
  {
    id: "linux-bible",
    title: "Linux Bible",
    author: "Christopher Negus",
    type: "book",
    difficulty: "beginner",
    topics: ["linux"],
    duration: "25h",
  },
  {
    id: "bash-guide",
    title: "The Bash Guide",
    author: "Community",
    type: "documentation",
    difficulty: "beginner",
    topics: ["bash", "shell"],
    duration: "8h",
  },
  {
    id: "github-actions-docs",
    title: "GitHub Actions Documentation",
    author: "GitHub",
    type: "documentation",
    difficulty: "beginner",
    topics: ["cicd"],
    duration: "10h",
  },
  {
    id: "argo-cd-docs",
    title: "Argo CD Documentation",
    author: "Argo Project",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["gitops", "kubernetes"],
    duration: "8h",
  },
  {
    id: "pulumi-docs",
    title: "Pulumi Documentation",
    author: "Pulumi",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["iac", "pulumi"],
    duration: "10h",
  },
  {
    id: "backstage-docs",
    title: "Backstage Documentation",
    author: "Spotify",
    type: "documentation",
    difficulty: "intermediate",
    topics: ["platform-engineering"],
    duration: "12h",
  },
];

export function getResourcesByTopic(topic: string): LearningResource[] {
  return resources.filter((r) => r.topics.includes(topic));
}

export function getResourcesByType(type: LearningResource["type"]): LearningResource[] {
  return resources.filter((r) => r.type === type);
}

export function getResourceCount(): number {
  return resources.length;
}
