export interface Milestone {
  id: string;
  title: string;
  description: string;
  dependencies: string[];
  estimatedDays: number;
  skills: string[];
  resources: string[];
}

export interface Roadmap {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  totalDays: number;
  milestones: Milestone[];
}

export const roadmaps: Roadmap[] = [
  {
    id: "ai-engineer",
    title: "AI Engineer",
    description: "Master AI engineering — LLMs, agents, RAG, MLOps",
    icon: "BrainCircuit",
    color: "accent-purple",
    totalDays: 180,
    milestones: [
      {
        id: "ml-fundamentals",
        title: "ML Fundamentals",
        description: "Supervised, unsupervised, feature engineering, evaluation",
        dependencies: [],
        estimatedDays: 21,
        skills: ["ml-fundamentals"],
        resources: ["hands-on-ml", "statistical-learning"],
      },
      {
        id: "deep-learning",
        title: "Deep Learning",
        description: "Neural networks, CNNs, RNNs, training pipelines",
        dependencies: ["ml-fundamentals"],
        estimatedDays: 21,
        skills: ["deep-learning"],
        resources: ["deep-learning-book", "fast-ai"],
      },
      {
        id: "transformers",
        title: "Transformers & Attention",
        description: "Attention mechanism, BERT, GPT architectures, fine-tuning",
        dependencies: ["deep-learning"],
        estimatedDays: 28,
        skills: ["transformers"],
        resources: ["attention-paper", "huggingface-nlp"],
      },
      {
        id: "llm-engineering",
        title: "LLM Engineering",
        description: "Prompt engineering, RAG, embeddings, vector databases",
        dependencies: ["transformers"],
        estimatedDays: 28,
        skills: ["llm-engineering"],
        resources: ["llm-apps", "langchain-docs"],
      },
      {
        id: "ai-agents",
        title: "AI Agents",
        description: "Agent architecture, tool use, memory, multi-agent systems",
        dependencies: ["llm-engineering"],
        estimatedDays: 28,
        skills: ["ai-agents"],
        resources: ["agent-patterns", "langgraph-docs"],
      },
      {
        id: "mlops",
        title: "MLOps & Production",
        description: "Experiment tracking, model serving, monitoring, A/B testing",
        dependencies: ["llm-engineering"],
        estimatedDays: 28,
        skills: ["mlops"],
        resources: ["mlops-book", "kubeflow-docs"],
      },
      {
        id: "ai-safety",
        title: "AI Safety & Evaluation",
        description: "Red teaming, alignment, benchmarks, responsible AI",
        dependencies: ["ai-agents"],
        estimatedDays: 14,
        skills: ["ai-safety"],
        resources: ["ai-safety-papers", "evals-framework"],
      },
      {
        id: "capstone",
        title: "Capstone: Production AI System",
        description: "Build and deploy a complete AI-powered application",
        dependencies: ["ai-agents", "mlops"],
        estimatedDays: 14,
        skills: ["ai-engineering"],
        resources: [],
      },
    ],
  },
  {
    id: "backend-architect",
    title: "Backend Architect",
    description: "Design and build production-grade distributed systems",
    icon: "Server",
    color: "accent-blue",
    totalDays: 180,
    milestones: [
      {
        id: "programming-core",
        title: "Core Programming",
        description: "TypeScript, Go, Rust fundamentals, functional programming",
        dependencies: [],
        estimatedDays: 21,
        skills: ["programming"],
        resources: ["ts-handbook", "go-book"],
      },
      {
        id: "databases",
        title: "Databases & Storage",
        description: "PostgreSQL, Redis, indexing, query optimization, sharding",
        dependencies: ["programming-core"],
        estimatedDays: 28,
        skills: ["databases"],
        resources: ["ddia", "pg-docs"],
      },
      {
        id: "api-design",
        title: "API Design",
        description: "REST, GraphQL, gRPC, versioning, documentation",
        dependencies: ["programming-core"],
        estimatedDays: 21,
        skills: ["api-design"],
        resources: ["api-design-book", "grpc-docs"],
      },
      {
        id: "microservices",
        title: "Microservices",
        description: "Service boundaries, messaging, orchestration, patterns",
        dependencies: ["api-design", "databases"],
        estimatedDays: 28,
        skills: ["microservices"],
        resources: ["microservices-patterns", "kafka-docs"],
      },
      {
        id: "distributed-systems",
        title: "Distributed Systems",
        description: "Consensus, consistency, partitioning, distributed transactions",
        dependencies: ["microservices"],
        estimatedDays: 28,
        skills: ["distributed-systems"],
        resources: ["mit-6824", "ddia"],
      },
      {
        id: "cloud-infra",
        title: "Cloud Infrastructure",
        description: "AWS/GCP core services, Terraform, serverless, container orchestration",
        dependencies: ["distributed-systems"],
        estimatedDays: 28,
        skills: ["cloud-infrastructure"],
        resources: ["aws-saa", "terraform-up"],
      },
      {
        id: "observability",
        title: "Observability",
        description: "Monitoring, tracing, logging, SLOs, incident response",
        dependencies: ["cloud-infra"],
        estimatedDays: 14,
        skills: ["observability"],
        resources: ["o11y-book", "grafana-docs"],
      },
      {
        id: "architect-capstone",
        title: "Capstone: Platform Design",
        description: "Design and implement a distributed platform from scratch",
        dependencies: ["observability"],
        estimatedDays: 14,
        skills: ["system-design"],
        resources: [],
      },
    ],
  },
  {
    id: "rust-engineer",
    title: "Rust Engineer",
    description: "Systems programming with Rust — from ownership to async",
    icon: "Code2",
    color: "accent-green",
    totalDays: 120,
    milestones: [
      {
        id: "rust-basics",
        title: "Rust Basics",
        description: "Ownership, borrowing, lifetimes, structs, enums, pattern matching",
        dependencies: [],
        estimatedDays: 21,
        skills: ["rust"],
        resources: ["rust-book", "rust-by-example"],
      },
      {
        id: "rust-intermediate",
        title: "Intermediate Rust",
        description: "Traits, generics, closures, iterators, error handling, modules",
        dependencies: ["rust-basics"],
        estimatedDays: 21,
        skills: ["rust"],
        resources: ["rust-book", "rustlings"],
      },
      {
        id: "rust-advanced",
        title: "Advanced Rust",
        description: "Unsafe Rust, FFI, macros, advanced types, Pin, interior mutability",
        dependencies: ["rust-intermediate"],
        estimatedDays: 28,
        skills: ["rust"],
        resources: ["rust-nomicon", "rust-atomics"],
      },
      {
        id: "rust-async",
        title: "Async Rust",
        description: "Futures, async/await, tokio, async traits, streaming",
        dependencies: ["rust-advanced"],
        estimatedDays: 21,
        skills: ["rust"],
        resources: ["async-rust-book", "tokio-docs"],
      },
      {
        id: "rust-capstone",
        title: "Capstone: Systems Tool",
        description: "Build a production-grade CLI tool, database driver, or networking library",
        dependencies: ["rust-async"],
        estimatedDays: 28,
        skills: ["rust"],
        resources: [],
      },
    ],
  },
  {
    id: "ml-engineer",
    title: "ML Engineer",
    description: "End-to-end machine learning engineering and deployment",
    icon: "Brain",
    color: "accent-cyan",
    totalDays: 150,
    milestones: [
      {
        id: "math-foundations",
        title: "Math Foundations",
        description: "Linear algebra, calculus, probability, statistics for ML",
        dependencies: [],
        estimatedDays: 21,
        skills: ["mathematics"],
        resources: ["essence-linalg", "statistical-thinking"],
      },
      {
        id: "ml-core",
        title: "ML Core",
        description: "Regression, classification, clustering, dimensionality reduction",
        dependencies: ["math-foundations"],
        estimatedDays: 28,
        skills: ["machine-learning"],
        resources: ["hands-on-ml", "sklearn-docs"],
      },
      {
        id: "deep-learning-ml",
        title: "Deep Learning",
        description: "Neural networks, CNNs, RNNs, GANs, PyTorch",
        dependencies: ["ml-core"],
        estimatedDays: 28,
        skills: ["deep-learning"],
        resources: ["d2l", "pytorch-docs"],
      },
      {
        id: "ml-pipelines",
        title: "ML Pipelines",
        description: "Feature engineering, data pipelines, experiment tracking, model registry",
        dependencies: ["ml-core"],
        estimatedDays: 21,
        skills: ["mlops"],
        resources: ["mlops-book", "mlflow-docs"],
      },
      {
        id: "ml-deployment",
        title: "ML Deployment",
        description: "Model serving, batch inference, A/B testing, monitoring drift",
        dependencies: ["ml-pipelines", "deep-learning-ml"],
        estimatedDays: 28,
        skills: ["mlops"],
        resources: ["ml-engineering", "kubeflow-docs"],
      },
      {
        id: "ml-capstone",
        title: "Capstone: ML System",
        description: "Build and deploy a complete ML system with monitoring",
        dependencies: ["ml-deployment"],
        estimatedDays: 21,
        skills: ["machine-learning", "mlops"],
        resources: [],
      },
    ],
  },
  {
    id: "devops-sre",
    title: "DevOps & SRE",
    description: "Infrastructure, CI/CD, reliability, and platform engineering",
    icon: "Container",
    color: "accent-amber",
    totalDays: 150,
    milestones: [
      {
        id: "linux-fundamentals",
        title: "Linux & Scripting",
        description: "Shell, process management, networking, bash scripting",
        dependencies: [],
        estimatedDays: 14,
        skills: ["programming"],
        resources: ["linux-bible", "bash-guide"],
      },
      {
        id: "containers",
        title: "Containers & Orchestration",
        description: "Docker, Kubernetes fundamentals, pod design, services",
        dependencies: ["linux-fundamentals"],
        estimatedDays: 28,
        skills: ["containers"],
        resources: ["docker-deep", "ckad-guide"],
      },
      {
        id: "cicd",
        title: "CI/CD",
        description: "GitHub Actions, GitOps, artifact management, deployment strategies",
        dependencies: ["containers"],
        estimatedDays: 21,
        skills: ["cicd"],
        resources: ["github-actions-docs", "argo-cd-docs"],
      },
      {
        id: "infra-as-code",
        title: "Infrastructure as Code",
        description: "Terraform, Pulumi, configuration management, secret management",
        dependencies: ["containers"],
        estimatedDays: 21,
        skills: ["infrastructure-as-code"],
        resources: ["terraform-up", "pulumi-docs"],
      },
      {
        id: "observability-sre",
        title: "Observability & SRE",
        description: "Monitoring, tracing, logging, SLOs, error budgets, incident management",
        dependencies: ["cicd", "infra-as-code"],
        estimatedDays: 28,
        skills: ["observability"],
        resources: ["sre-book", "o11y-book"],
      },
      {
        id: "platform-engineering",
        title: "Platform Engineering",
        description: "Internal developer platforms, backstage, service catalogs",
        dependencies: ["observability-sre"],
        estimatedDays: 21,
        skills: ["platform-engineering"],
        resources: ["platform-eng-book", "backstage-docs"],
      },
      {
        id: "devops-capstone",
        title: "Capstone: Platform",
        description: "Design and implement a complete internal developer platform",
        dependencies: ["platform-engineering"],
        estimatedDays: 21,
        skills: ["devops"],
        resources: [],
      },
    ],
  },
];

export function getRoadmapById(id: string): Roadmap | undefined {
  return roadmaps.find((r) => r.id === id);
}

export function getMilestonesForSkill(skillId: string): Milestone[] {
  return roadmaps.flatMap((r) => r.milestones.filter((m) => m.skills.includes(skillId)));
}
